### ISSUE TITLE
neovim 0.7.0 support

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#34]
Neovim has released v0.7.0 as the latest stable version. And there are many new feature and bug fixes.

https://github.com/neovim/neovim/releases/tag/v0.7.0

### TODO

- [ ] Rewrite the ci test, as "press enter" never block the headless neovim now. (https://github.com/neovim/neovim/commit/5b34c2ab73d62431f391d454e68a84332148d609)
- [ ] Use new Lua API to write auto command
- [ ] Use new Lua API to set keymap
- [ ] Use new Lua API to map Lua function to keymap
- [ ] Add description for all keymaps
