### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#8]
# Prepare for 4.0.0 

## Document

- [x] Introducing my workflow, instead of list of the plugins usage.
- [x] Rewrite the README

## Plugins

- [ ] ~~Write a script to help reload the neovim configuration~~ [STUCK][^1].
- [x] Rewrite the plugin structure
- [x] Simplify the colorscheme
- [x] Use a global filetype list for treesitter and lspconfig.
- [x] Try lazy-loading everything, based on Lua `module` syntax.
- [x] Add a spelling checker and dictionary completion.
- [x] #40
- [ ] #41

[^1]: I don't know how to open new neovim inside the old neovim.
